name: Auto Sitemap Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (if any)
        run: npm install || echo "No dependencies"

      - name: Generate sitemap.xml
        run: npm run generate-sitemap

      - name: Commit & push sitemap.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update sitemap.xml"
            git push https://Oprockyvai:${{ secrets.GH_PAT }}@github.com/Oprockyvai/MY-DESHI-FLIX.git HEAD:main
          else
            echo "No changes to commit"
          fi