name: Generate Sitemap

on:
  schedule:
    - cron: "0 0 * * 0" # প্রতি রবিবার 12:00 AM UTC তে রান করবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Generate sitemap
        run: node generate-sitemap.js

      - name: Commit and push sitemap
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git add sitemap.xml
    git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
    git push https://${{ secrets.PAT_TOKEN }}@github.com/<Oprockyvai>/<MY-DESHI-FLIX>.git HEAD:main